### ISSUE TITLE
Fix --inspect for multiple workers

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#1019]
Different workers need separate ports
See: https://github.com/metarhia/impress/blob/a55b4d5bee2529730e7f6356f8501dfbc0880be9/lib/workers.js#L12

@nechaido @belochub please assign somebody

**Comment by tshemsedinov** [comment]
Now all keys will be passed to workers, for example: `--prof` but `--inspect` need to be changed

**Comment by lundibundi** [comment]
Can be done via `--inspect=0` as proposed by @belochub.
