### ISSUE TITLE
Application 'stopped' event is not emitted

### ISSUE THREAD

**Issue by lundibundi** [metarhia/impress#1165]
This can be easily observed by adding this 
```js
application.on('stopped', () => {
  console.warn('Application stopped');
});
```
to the lib of example application and then either starting/stopping it or running tests.

Impress tries to emit 'stopped' event in the core.js#594 but at that point, there are no more applications in the list.

**Comment by tshemsedinov** [comment]
Not relevant for v2.x. Now we have `start/stop` handlers for `lib` and `domain` modules, see example: https://github.com/metarhia/Example/blob/f9248b81d14e0434b7a25b751ce6eb46fdeedb34/application/domain/remote/start.js
