### ISSUE TITLE
`process.on('warning')` may happen earlier than `impress.log` will be initialized

### ISSUE THREAD

**Issue by o-rumiantsev** [metarhia/impress#1176]
https://github.com/metarhia/impress/blob/eee470dabcc009204fd0b11449628a0b1499243f/lib/core.js#L127-L130

For example, if `fs.promises` are used in project, there might be `warning` event emitted by `process` before `impress` will be started, and therefore logger won't be initialized. So there will be an error thrown: `TypeError: Cannot read property 'warn' of undefined`

**Comment by tshemsedinov** [comment]
Need an example to reproduce this bug

**Comment by lundibundi** [comment]
@tshemsedinov If you add a dependency that uses experimental api or in some other way causes a warning (i.e. add `require('fs').promises` in Node.js 10 to some dependency) it will crash impress started with `npm test` or `./server.sh` with
![Screenshot from 2019-06-25 21-20-24](https://user-images.githubusercontent.com/9109612/60123117-5d1fe680-978f-11e9-8bbb-729b57c77b65.png)
