### ISSUE TITLE
Invalid file size comparison 

### ISSUE THREAD

**Issue by mille-nium** [metarhia/impress#1187]
As long as `cacheMaxFileSize` is a string (file size in format like this `'10mb'`) and `stats.size` is a number (file size in bytes), the comparison here leads to incorrect behaviour:
https://github.com/metarhia/impress/blob/a9f5db25ebce72596025f7dc5d16a62d860a9dd1/lib/client.js#L712-L713

**Comment by tshemsedinov** [comment]
Need to debug this because config files are additionally processed after loading.

**Comment by mille-nium** [comment]
@tshemsedinov I've had, after loading, as well as later in tests `application.config.sections.files` is an object similar to one in config file:
![image](https://user-images.githubusercontent.com/31672093/61833605-7e9eeb80-ae7d-11e9-9bc3-f8a2cbb940b0.png)

**Comment by lundibundi** [comment]
`common.sizeToBytes()` must be used here similar to the way `Duration` is used in other config files, but it's not exposed (at least not directly) to configs currently. Configs should have a separate sandbox with such utils exposed directly and separately from the main sandbox of the Application.

**Comment by tshemsedinov** [comment]
Not relevant for 2.x but will be will be taken into account when we will implement cache limits in future.
