### ISSUE TITLE
End response after basic authentication

### ISSUE THREAD

**Issue by mille-nium** [metarhia/impress#1189]
I'm not sure which scenario is proper for basic authentication, however if I do a test with `GET` request with header `Authorization`, although the file handler is executed and basic authentication is completely passed, response won't be ended due to the `return` statement here
https://github.com/metarhia/impress/blob/a9f5db25ebce72596025f7dc5d16a62d860a9dd1/lib/client.js#L255-L258
So, if I'm not mistaken, in case of basic authentication the response will be ended only if authentication won't pass and `401 Unauthorized` status response code will be sent. Otherwise `client.res.end()` will never be invoked

**Comment by tshemsedinov** [comment]
Basic auth support deprecated in v2.x
