### ISSUE TITLE
No files in `client.upload()`

### ISSUE THREAD

**Issue by mille-nium** [metarhia/impress#1190]
IIUC, this will only work in case, if request `Content-Type` header isn't `multipart/form-data`
https://github.com/metarhia/impress/blob/a9f5db25ebce72596025f7dc5d16a62d860a9dd1/lib/client.js#L856-L860

Otherwise, if request `Content-Type` header is `multipart/form-data`, but the form was without files, `client.files` will be an empty object.
https://github.com/metarhia/impress/blob/a9f5db25ebce72596025f7dc5d16a62d860a9dd1/lib/application.js#L579-L586

If I'm not mistaken, neither `if` condition won't be true, nor the `for` loop in `client.upload` won't be executed, so that `callback` in `client.upload` won't be called.

**Comment by tshemsedinov** [comment]
Forms are not supported in 2.x, all client-server interactions, forms and file transfers should be implemented with RPC API, not http-style methods.
