### ISSUE TITLE
Dependency hell: possible missed dependency

### ISSUE THREAD

**Issue by scilganon** [metarhia/impress#1197]
npm doesn't have flat deps tree, it can lead to following:

> package **A** have dependent **B**; once developers of **A** just remove **B** as redundant and after updating application `api.registry.require()` can fall down

what about to restrict possible load to explicitly existed in `package.json`? or just show warn dev to force him install package

---

it can be got from:

```
$> npm ls --depth 0 --prod --parseable
```

**Comment by tshemsedinov** [comment]
I can't catch you idea @scilganon but we are not supporting random dependencies, everything in registry will be from metarhia stack, node internal or strongly checked before adding to registry.

**Comment by tshemsedinov** [comment]
Not actual because dependency loader changed a lot
