### ISSUE TITLE
No way to assign access rights per method name

### ISSUE THREAD

**Issue by donDonald** [metarhia/impress#1208]
Assume I have a url specifying get and post methods:
/www/users/get.js 
/www/users/post.js
/www/users/access.js

Here is only access.js is possible thought I want to have separate access rights for get and post request. I might want to provide access to get for any guest and to post only for admin.
I see no option to get it done right now.

**Comment by tshemsedinov** [comment]
Yes, now you can separate access rights for endpoints just creating separate endpoint (folder) with `post.js` and `access.js`. Note that in 2.0 we will change this behavior.

**Comment by donDonald** [comment]
Cool, closing this issue

**Comment by tshemsedinov** [comment]
Thanks for patience, we are going to change paradigm of impress now and working on new and minimalist core...
