### ISSUE TITLE
Research: compile TypeScript on-the-fly

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#1269]
Improve loader to compile single TypeScript file from `.ts` on-the-fly in memory but tests will use `tsc` for whole project

**Comment by lundibundi** [comment]
The typescript can incrementally compile files on-the-fly but the whole project needs to be in memory [of the compiler]. It is possible to compile a single file only if it doesn't have any dependencies (which is rarely the case).

The manual recompilation\trigger can be done via rich API of the `tsc` (as it is done by multiple IDE) or via `tsc --watch` automatically if the project structure is known to the tsc.
