### ISSUE TITLE
Change namespaces

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#1279]
It's now a single namespace `application.submoduleName` for all submodules from `application/lib` and `application/domain` but it will be better to separate namespaces to avoid name conflict to: `lib.submoduleName` and `domain.submoduleName`.

**Comment by lundibundi** [comment]
IMO, it has to at least include the module's structure as well (either automatically or with the ability to do so manually):
```
application
--| folder1
   --| a.js 
   --| b.js 
--| folder2
   --| a.js 
--| file.js
```
=>
```
api = {
  lib: {
    folder1: { a: { ... }, b: { ... } },
    folder2: { a: { ... } },
    file: { ... }
  }
  ...
}
