### ISSUE TITLE
Use "this" in methods

### ISSUE THREAD

**Issue by Dmitrii8891** [metarhia/impress#1344]
Can I use "this" inside file?
It's normal for Impress?

For example 
>({
   async hello(name) {
      return "Hello user " +  name;
   },
   async test(name) {
      return this.hello(name);
   },
})

Or better use that 

> ({
   async hello(name) {
        return "Hello user " +  name;
   },
   async test(name) {
      return domain.test.helper.hello(name);
   },
})

**Comment by tshemsedinov** [comment]
After this PR https://github.com/metarhia/impress/pull/1350 you can do both cases.

**Comment by tshemsedinov** [comment]
See examples: https://github.com/metarhia/Example/blob/master/application/lib/example/start.js
