### ISSUE TITLE
Add access to the environment variables from configs

### ISSUE THREAD

**Issue by imnetcat** [metarhia/impress#1466]
I'm frustrated when I can't set port in config like "process.env.PORT || 8000".

I would like to add support for heroku & may be other that using process.env.PORT

The best solution to this problem is to pass the port to the sandbox, which is then passed to the worker config.

**Comment by imnetcat** [comment]
solution above gives us the opportunity write in the config like this
```
...
this.PORT || 8000
...
```

**Comment by tshemsedinov** [comment]
In node.js starter kit we can just put such expressions to config: `({ port: process.env.PORT })` but after extracting it ti metavm we need to pass process to sandbox.
