### ISSUE TITLE
TypeError while watching files in WSL 2

### ISSUE THREAD

**Issue by rohiievych** [metarhia/impress#1605]
**Describe the bug**
Type error occurs persistently in the file watch section while running in Ubuntu under Windows Subsystem Linux 2.

**To Reproduce**
Run Impress application under WSL 2 and change source file, e.g. Example/application/api/geo.1.js.

**Expected behavior**
No errors occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/13386556/125207943-36f71180-e298-11eb-9ce5-9291d8f46a07.png)

**Desktop (please complete the following information):**

- OS: [Windows 10 64-bit, Ubuntu 18.04.5 LTS under WSL 2]
- Node.js version [14.10.1]
- Impress version [2.4.2]

**Additional context**

- First observation from offical Node docs: The fs.watch API is not 100% consistent across platforms.
- Second observation: error occurs only in WSL 2, no errors were noticed in Powershell or Git bash.
- Third observation: OS fires multiple FS calls, one on target file path and another on its parent folder path.
- Fourth observation: error occurs due to absence of a separator in relative parent folder path, what leads to undefined place on application class instance.

Possible solution: check relative path of watched file.

**Comment by tshemsedinov** [comment]
I have no WSL environment so can't reproduce this. Can you please collect mode debug info, for example add following line before load method call and send me log files?
```
console.log({ place, filePath, stat, sep: path.sep, relPath, sepIndex });
```

**Comment by rohiievych** [comment]
@tshemsedinov
Here is a clear log related to this issue:
[2021-07-12-W1.log](https://github.com/metarhia/impress/files/6799762/2021-07-12-W1.log)

**Comment by dimon-durak** [comment]
I install metarhia/Example on WSL2 running Ubuntu 20.04

And it's work fine.

```
wsl --set-default-version 2

wsl --unregister wave
wsl --import wave C:\~\virtual\wsl\wave C:\~\virtual\wsl\ubuntu-20.04.tar.gz

wsl
```

```
adduser wave
usermod -aG sudo wave

su  wave

sudo apt update -y
sudo apt upgrade -y

sudo apt install build-essential -y

wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
source ~/.bashrc

nvm install v15.14.0

cd ~
git clone https://github.com/metarhia/Example.git wave
cd wave
npm install
node server.js
```

**Comment by dimon-durak** [comment]
I install metarhia/Example on WSL2 running Ubuntu 20.04

And hot-reload works fine.

![image](https://user-images.githubusercontent.com/1760096/125419671-7ee585ac-bf97-40e4-a1c2-0a10788ab8c2.png)


```powershell
wsl --set-default-version 2

wsl --unregister wave
wsl --import wave C:\~\virtual\wsl\wave C:\~\virtual\wsl\ubuntu-20.04.tar.gz

wsl
``` 

```bash
adduser wave
usermod -aG sudo wave

su  wave

sudo apt update -y
sudo apt upgrade -y

sudo apt install build-essential -y

wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
source ~/.bashrc

nvm install v15.14.0

cd ~
git clone https://github.com/metarhia/Example.git wave
cd wave
npm install
node server.js
```

**Comment by naliferov** [comment]
OS: **Windows 10 WSL2**, which is running **Ubuntu 20.04**
Node.js version: **16.0.0**
Impress version: **3.0.2**

I have installed metarhia/Example using the commands mentioned in the previous post. 
I started the server and made changes to the files. Here's the log after making these changes:
```
Start: /home/x8core/Example/application
15:21:40  W1   debug   Connect to pg
15:21:40  W1   debug   Connect to redis
15:21:40  W4   info    Application started in worker 4
15:21:40  W2   info    Application started in worker 2
15:21:40  W3   info    Application started in worker 3
15:21:40  W2   info    Listen port 8001
15:21:40  W3   info    Listen port 8002
15:21:40  W1   info    Application started in worker 1
15:21:40  W1   info    Listen port 8000
15:21:40  W5   info    Application started in worker 5
15:21:40  W0   info    App started: /home/x8core/Example/application
15:24:04  W1   debug   Reload: /api/.geo.1.js.swp
15:24:10  W1   debug   Reload: /api/.geo.1.js.swp
15:24:12  W1   debug   Deleted: /api/.geo.1.js.swp
15:24:12  W1   debug   Reload: /api/geo.1.js
15:49:36  W1   debug   Reload: /api/.geo.1.js.swp
15:49:47  W1   debug   Deleted: /api/.geo.1.js.swp
15:49:48  W1   debug   Reload: /api/.geo.1.js.swp
15:49:51  W1   debug   Reload: /api/.geo.1.js.swp
15:49:53  W1   debug   Deleted: /api/.geo.1.js.swp
15:49:53  W1   debug   Reload: /api/geo.1.js
15:50:46  W1   debug   Reload: /api/.hook.1.js.swp
15:50:49  W1   debug   Reload: /api/.hook.1.js.swp
15:50:50  W1   debug   Deleted: /api/.hook.1.js.swp
15:50:50  W1   debug   Reload: /api/hook.1.js
```

**Comment by tshemsedinov** [comment]
The bug seems to have gone away
