### ISSUE TITLE
Type validation parameter with name "type"

### ISSUE THREAD

**Issue by sarnakov** [metarhia/impress#1606]
**Description**
You can`t have a method with a field named 'type'. 

**To Reproduce**
You need just make an API method with validation, like this:
parameters: {
  type: 'string',
}

**In result**
I have an error: [Error: Invalid parameters type: Field "value" is not of expected type: string]

**Comment by tshemsedinov** [comment]
type is a reserved word in metaschema and a bad naming for any subject domain, so we will improve error message but this case is not a bug

**Comment by sarnakov** [comment]
Ok, thanks.
