### ISSUE TITLE
DI error in custom worker thread

### ISSUE THREAD

**Issue by rohiievych** [metarhia/impress#1626]
**Description of the bug**
It's possible to run worker outside of sandbox, so no node or lib dependecies are visible.
Also you can use require or import instructions, what possibly can break the DI mechanism of Impress.

**To Reproduce**
Create a lib module with embedded worker named `embeddedWorker.js`:
```js
(class EmbeddedWorker extends node.worker.Worker {

  constructor(options) {
    const workerScript = `(${EmbeddedWorker.#run.toString()})()`;
    super(workerScript, { ...options, eval: true });
  }

  // This function is run in worker thread
  static #run = async () => {
    const { parentPort } = await import('node:worker_threads');
    console.log('Running in embedded worker');
    console.log(node);

    parentPort.once('message', (message) => {
      parentPort.postMessage(message);
    });
  };
});
```
Create an api interface `testWorker.js` to test the lib above:
```js
({
  access: 'public',
  method: async (pingMessage) => {
    const worker = new lib.embeddedWorker();
    worker.postMessage(pingMessage);
    const pongMessage = await new Promise(resolve => worker.once('message', resolve));
    return { result: pongMessage };
  }
});
```
Start impress server and run api test in browser console:
`await api.repositoryServer.testWorker('Hello from embedded worker!');`

Look at server logs and see an errors saying `ReferenceError: node is not defined`
```
$ node server.js
15:24:07  W1   info    Listen port 8000 in worker 1
15:24:07  W2   info    Application started in worker 2
15:24:07  W1   info    Application started in worker 1
Running in embedded worker
(node:22000) UnhandledPromiseRejectionWarning: ReferenceError: node is not defined
    at [worker eval]:4:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

To see the correct behavior remove `console.log(node);` from the worker code in `embeddedWorker.js` and rerun test:
```js
await api.repositoryServer.testWorker('Hello from embedded worker!');
{result: "Hello from embedded worker!"}
```
You can see message response from worker thread in browser console as well as no errors in server logs:
```
Running in embedded worker
15:48:02  W1   log     127.0.0.1        repositoryServer/testWorker
```

**Expected behavior**
It should be possible to use node, lib or other injected variables inside of worker thread without errors.
DI should work correct inside of worker thread.

**Screenshots**
![image](https://user-images.githubusercontent.com/13386556/129385591-974f890a-b693-44a2-b90a-ecaec22ad6a3.png)

**Desktop (please complete the following information):**

- OS: Windows 10 x64
- Node.js version 14.16.1
- Impress version 2.5.2

**Comment by georgolden** [comment]
Creating an instance of a worker means to run node.js isolated with only native heap memory shared. There will be obviously no sandbox inside another separated thread. You can only become data with `message.port` from worker or via `SharedArrayBuffer`. It does not break DI because you have no access to a sandbox itself.
If you want to start another worker - no problem, do that, but there should be outside your application logic.

`Suggestion`: remove `worke_threads` and other unnecessary node internal libs from application sandbox context.

**Comment by rohiievych** [comment]
> Creating an instance of a worker means to run node.js isolated with only native heap memory shared. There will be obviously no sandbox inside another separated thread. You can only become data with `message.port` from worker or via `SharedArrayBuffer`. It does not break DI because you have no access to a sandbox itself.
> If you want to start another worker - no problem, do that, but there should be outside your application logic.
> 
> `Suggestion`: remove `worke_threads` and other unnecessary node internal libs from application sandbox context.
> @tshemsedinov Remove?

It's better to integrate worker thread invocation and share the context automatically. Otherwise you won't be able to parallelize effectively CPU-intensive work using application code. You can simply have a lib, which is reused inside a worker. In this case you'll have to duplicate the code.
See [this issue](https://github.com/metarhia/impress/issues/1627).

**Comment by tshemsedinov** [comment]
I going to deny `require/import` and remove access to `node:worker_threads` at all. Instead we need a highlevel method to parallelize CPU-intensive tasks using impress preallocated pool of threads. @rohiievych @georgolden

**Comment by tshemsedinov** [comment]
Without modifying impress sources call to`import('node:worker_threads')` throws `ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING` @rohiievych

**Comment by rohiievych** [comment]
> Without modifying impress sources call to`import('node:worker_threads')` throws `ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING` @rohiievych

I have enabled { type: "module" } in package.json, maybe that is the reason.
Also I see the official docs say this error occurs while creating vm scripts without the following option:

> `importModuleDynamically` <Function> Called during evaluation of this module when import() is called. If this option is not specified, calls to import() will reject with ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING.

**Comment by tshemsedinov** [comment]
`node.worker` will be deprecated in `2.7.0` @rohiievych @georgolden

**Comment by tshemsedinov** [comment]
See related changes in #1649, #1650, #1644
