### ISSUE TITLE
Worker thread module

### ISSUE THREAD

**Issue by rohiievych** [metarhia/impress#1627]
**What do we need?**
Although Impress is parallelized for requests, sometimes we need to perform CPU-intensive operations like file compression or sofisticated calculations. The best solution to optimize this kind of work is to leverage worker threads. For now it's possible to create custom workers with Impress, but it seems to be too tricky. That's why we need to introduce worker thread modules.

**Possible solution**
Create a new type of lib/domain module or extend the existing contract to be able to run such modules in dedicated worker thread reusing a pool of workers. This can help to optimize CPU-intensive tasks that can be executed parallelly.
Conventionally it can be a filename suffix as part of a contract, e.g:
`lib/intensiveTask.worker.js`
```js
(baseNumber) => {
  console.log('Running in embedded worker');
  let result = 0;
  for (let i = Math.pow(baseNumber, 7); i >= 0; --i) {
    result += Math.atan(i) * Math.tan(i);
  }
  return result;
};
```
Under the hood Impress can run this code in a worker from a pool and wrap `node.worker.parentPort.postMessage(result)` in Promise as a result for caller, e.g:
`api/iface.1/calculateIntensiveTask.js`
```js
({
  access: 'public',
  method: async ({ firstNum, secondNum }) => {
    const results = await Promise.all([
      lib.intensiveTaskWorker(firstNum),
      lib.intensiveTaskWorker(secondNum)
    ]);
    return { results };
  }
});
```

**Current alternatives**
For now it's possible to use regular module contract to run dedicated worker thread, but it's kind of workaround and no worker pool is used:
`lib/embeddedWorker.js`
```js
(class EmbeddedWorker extends node.worker.Worker {

  constructor(options) {
    const workerScript = `(${EmbeddedWorker.#run.toString()})()`;
    super(workerScript, { ...options, eval: true });
  }

  // This function is run in worker thread
  static #run = async () => {
    const { parentPort } = await import('node:worker_threads');
    console.log('Running in embedded worker');

    parentPort.once('message', (message) => {
      parentPort.postMessage(message);
    });
  };
});
```
Usage:
`api/iface.1/testWorker.js`
```js
({
  access: 'public',
  method: async (pingMessage) => {
    const worker = new lib.embeddedWorker();
    worker.postMessage(pingMessage);
    const pongMessage = await new Promise(resolve => worker.once('message', resolve));
    return { result: pongMessage };
  }
});
```

Refs: #1626

**Comment by tshemsedinov** [comment]
We have a thread pool in impress (used only for scheduled tasks), so we need just a tool to run any call in workers in this poll, we can add API for this, example:
```js
application.invoke(domain.module1.methodName, { arg1: 'value1' });
```

**Comment by rohiievych** [comment]
> We have a thread pool in impress (used only for scheduled tasks), so we need just a tool to run any call in workers in this poll, we can add API for this, example:
> 
> ```js
> const res = await application.invoke(domain.module1.methodName, { arg1: 'value1' });
> ```

Yes, we can do it in this way and I'd suggest to create a new class called Thread that extends native Worker and implements Thenable object, so that we can use worker instance to terminate underlying script execution and automatically restart worker or to read worker specific data like threadId.
It's suitable to call this tool as *thread* to emphasise it's parallelism.

Termination example:
```js
const thread = application.thread(domain.module1.methodName, { arg1: 'value1' });
await thread.terminate();
```
Reading worker id example:
```js
const thread = application.thread(domain.module1.methodName, { arg1: 'value1' });
console.log(thread.threadId);
```
Getting worker result:
```js
const thread = application.thread(domain.module1.methodName, { arg1: 'value1' });
const result = await thread;
```
or just
```js
const result = await application.thread(domain.module1.methodName, { arg1: 'value1' });
```
