### ISSUE TITLE
Missing timers/promises API from node.timers

### ISSUE THREAD

**Issue by lundibundi** [metarhia/impress#1708]
**Describe the bug**
node.timers API https://nodejs.org/api/timers.html#timerspromisessettimeoutdelay-value-options is not available under
`node.timers.promises`

**To Reproduce**
`node.timers.promises.setTimeout()` - TypeError: Cannot read property 'setTimeout' of undefined

**Expected behavior**
It is possible to use this Node.js API.

**Desktop (please complete the following information):**

- OS: Linux zou 5.15.13-arch1-1 SMP PREEMPT Wed, 05 Jan 2022 16:20:59 +0000 x86_64 GNU/Linux
- Node.js version 14.18.2
- Impress version 2.6.6

**Comment by tshemsedinov** [comment]
Fixed in https://github.com/metarhia/impress/pull/1850
