### ISSUE TITLE
Planner not starts tasks

### ISSUE THREAD

**Issue by MidoMiddle** [metarhia/impress#1779]
### Impress and Node.js versions

16.15.0

### Platform

macos

### Describe the bug

After starting of an app, a tasks is not added to:
```javascript
constructor() {
    this.tasks = new Map();
}
```
After manual add new tasks, start does not schedule, because no tasks in ```this.tasks```
but .json files has been created

### To Reproduce

In Example do:

```javascript
// lib / task1 / start.js
await application.scheduler.add({
        name: 'name',
        every: '5s',
        args: { i: 2 },
        run: 'lib.task1.f1',
      });
```

```javascript
// lib / task1 / f1.js
async (args) => {
  console.debug('lib.task1.f1', args);
  await metarhia.metautil.delay(1000);
};
```

**Comment by tshemsedinov** [comment]
Done in #1780 and #1781
