### ISSUE TITLE
Get request to root static directory generates 404

### ISSUE THREAD

**Issue by leonpolak** [metarhia/impress#1788]
### Impress and Node.js versions

Impress 3.0.0-alpha.5, Node 18.4.0

### Platform

Windows

### Describe the bug

GET request to root static directory, like http://localhost:8000/ redirects to http://localhost:8001/  and generates 404 error.

`{"error":{"message":"Not Found","code":404}}`

GET request to http://localhost:8001/index.html works fine

**Comment by tshemsedinov** [comment]
Can't reproduce this for `3.0.0-alpha.8` @leonpolak

**Comment by tshemsedinov** [comment]
Fixed in [v3.0.0-alpha.14](https://github.com/metarhia/impress/releases/tag/v3.0.0-alpha.14)
