### ISSUE TITLE
Issue after migration to v3

### ISSUE THREAD

**Issue by sarnakov** [metarhia/impress#1884]
### Impress and Node.js versions

impress: 3.0.2, node 16.19.1

### Platform

22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64

### Describe the bug

After upgrading impress from version 2.6.10 to 3.0.2 I'm receiving an error:
```
Failed to execute method: No thread available Error: No thread available
  /node_modules/impress/impress.js:97:23
  async invoke (/node_modules/impress/impress.js:96:20)
```

### Additional context

Could somebody explain or hint at what could cause such an error or why it happens?

**Comment by tshemsedinov** [comment]
Check application/config/server.js
See example https://github.com/metarhia/Example/blob/master/application/config/server.js
