### ISSUE TITLE
Process ignores signals and does not stop

### ISSUE THREAD

**Issue by timursevimli** [metarhia/impress#1968]
### Impress and Node.js versions

Impress v3.0.0.0 and node v20.13.1

### Platform

Darwin (MacOS Sonoma)

### Describe the bug

The process ignores signals such as SIGINT, TERMINATE, and SIGTERM. After receiving one of these signals, an error occurs, causing it to ignore all events, including CTRL+C. The only option left is to stop the process by using the KILL signal.

### To Reproduce

Launch impress process and send any one of these signals like SIGINT, TERMINATE or SIGTERM.
After an error occurs, try calling CTRL + C.

Note: To exit the impress process completely, send the KILL signal.

### Expected behavior

Successfully graceful shutdown

### Screenshots

When using SIGINT signal for process by name of "impress", an error occurs:
![Screenshot 2024-05-17 at 14 56 35](https://github.com/metarhia/impress/assets/66042015/6e789c14-b03f-4f11-b135-87daced32208)

After an error occurs, CTRL + C launches the "graceful shutdown" mechanism, but even this does not help to exit the process:
![Screenshot 2024-05-17 at 14 53 36](https://github.com/metarhia/impress/assets/66042015/cb1841ad-2b26-4c38-93d2-009ab52c3e05)

Note: I call CTRL + C 4 times

**Comment by tshemsedinov** [comment]
It works well in 3.0.15 for me

**Comment by timursevimli** [comment]
This is impossible, instead of using CTRL + C, try passing the SIGINT signal using htop for example
