### ISSUE TITLE
Implement debugger support for child processes

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/Impress#299]

**Comment by tshemsedinov** [comment]
https://github.com/node-inspector/node-inspector это средство для отладки, если кому интересно, можно взяться за изучение node-inspector и реализацию его поддержки в Impress, если что будет непонятно, помогу конечно. Кто возьмется? @aagafonov, @j-martyn, @johnbizokk, @ReasonX7 ?

**Comment by j-martyn** [comment]
Я вчера делал попытки дебажить, в том числе при помощи node-inspector.
Дебаг даже работает, если запускать `node.exe --debug-brk=5858 server.js`.
В консоль в итоге пишет, что HTTP слушается, но сервер не отвечает.
Если через `node.exe --debug=5858 server.js` запускать, то дебаг не работает, он HTTP отвечает.
Надо разбираться. Тут может проблема из-за того что приложение работает в дочернем процессе, я в это еще не совсем вник, надо разбираться.
Хорошо работает такая штука Spy-js, это, я бы сказал, пост-дебаг. Можно смотреть в реалтайме что выполнялось, по каким событиям, как долго, и что именно - если есть if-else в коде, оно подсветит именно тот код, который выполнился.

**Comment by j-martyn** [comment]
Да, круто! С strategy: 'single' в config/scale.js заработало!

**Comment by tshemsedinov** [comment]
Да, ```node-inspector``` не поддерживает многопоточного режима и библиотеку ```cluster```, см. тут мою переписку с автором https://toster.ru/q/213165 Можешь там откомментить если что, или у него спрашивать прямо, шарящий мужик.

**Comment by aqrln** [comment]
I think we can count `node-inspector` as an obsolete and deprecated software. It hasn't been updated since spring and doesn't work with current Node.js versions. But Node now has V8 inspector built-in and it would be nice to support integration with it.

**Comment by tshemsedinov** [comment]
To add `--inspect` in workers we can specify debugger port in `config/server.js` for each server as `inspect` field (optional), example: `{ ... ports: [80], ... inspect: 9000 ... }`
If server record have multiple ports, for example: `port: [80, 81]` debugger port will be incremented: 9000, 9001, and so on.
