### ISSUE TITLE
Make it possible to run specified setup scripts synchronously

### ISSUE THREAD

**Issue by aqrln** [metarhia/impress#490]
Make it possible to run specified setup scripts synchronously so that those of them which interact with a person who deploys an app (like [this one](https://github.com/tshemsedinov/impress/blob/master/applications/example/setup/security.renameToJs)) do not interfere with each other prompting user simultaneously and messing up each other's console dialogs.

**Comment by tshemsedinov** [comment]
Not relevant for impress 2.x
