### ISSUE TITLE
Oracle database plugin for Impress Application Server?

### ISSUE THREAD

**Issue by stokaboka** [metarhia/impress#501]
subj...

I made for myself a small plugin for [OracleDb](https://www.npmjs.com/package/oracledb)
it works, but you need to check for updates and enclose plugin

you have any plans to support drivers for oracle DB ?

**Comment by tshemsedinov** [comment]
@stokaboka ok, it would be great to have Oracle driver in Impress, I'll review it and merge into ours monolith )))

**Comment by stokaboka** [comment]
i use [oracledb](https://www.npmjs.com/package/oracledb) and [simple-oracledb](https://www.npmjs.com/package/simple-oracledb)

oracledb need [Oracle Instant Client](http://www.oracle.com/technetwork/database/features/instant-client/index-097480.html) or installed Oracle server . I use OIC, the server is running on a different host

I'm still testing a basic DML operation (sel, ins, ups, del) it is not yet known how the driver is under the Impress with a number of clients (only while I test myself)

see attached files...
[db.oracle.js.txt](https://github.com/metarhia/Impress/files/210017/db.oracle.js.txt)
[oracle_delete_sample.js.txt](https://github.com/metarhia/Impress/files/210019/oracle_delete_sample.js.txt)
[oracle_insert_sample.js.txt](https://github.com/metarhia/Impress/files/210020/oracle_insert_sample.js.txt)
[oracle_select_sample.js.txt](https://github.com/metarhia/Impress/files/210018/oracle_select_sample.js.txt)
[oracle_update_sample.js.txt](https://github.com/metarhia/Impress/files/210021/oracle_update_sample.js.txt)

**Comment by tshemsedinov** [comment]
Done, duplicate issue https://github.com/metarhia/impress/issues/829
