### ISSUE TITLE
IAS applications installation

### ISSUE THREAD

**Issue by bolein** [metarhia/impress#517]
Impress applications should be installed with the application server itself.

For the time this issue is created, we had to install each application separately using npm. This may be unpleasant if we have many applications or distributing the server itself as a dependency.

I solved it for myself using the following post install script:

``` JS
  "scripts": {
    "postinstall": "cd applications/myapp && npm install"
  }
```

Although, for my opinion, this option should be bundled with the IAS.

**Comment by tshemsedinov** [comment]
In 0.3 IAS will have own packet manager, app manager and dependency manager, all in one
