### ISSUE TITLE
Move Impress CLI to the Impress core

### ISSUE THREAD

**Issue by aqrln** [metarhia/impress#528]
We can move the CLI tool to the Impress codebase so that it can reuse libraries from IAS and have direct access to it. This will allow more fine-grained control over IAS from the command line and will simplify implementation of new commands for scaffolding, managing separate applications etc. It will also allow to use the `impress` command as an npm script locally in a project right after installing Impress as a dependency to `node_modules` which is more convenient for development. Scripts that install IAS as a service will then be either moved to a new package (`impress-service`, for example) or placed together with deployment scripts.

**Comment by tshemsedinov** [comment]
We need CLI command `impress` visible everywhere in *nix command line like `service` or `chkconfig`, not an `npm` command.

**Comment by tshemsedinov** [comment]
Not relevant for v2.x
