### ISSUE TITLE
Rearrange global namespaces

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#530]
- Put timers to `api.timers`, `console.*` to `api.con.*` and other global libraries.
- Deprecate `require` at all.
- Move `JSON.*` to `api.json.*`
- Move `Math.*` to `api.math.*`
- Move `RegExp` to `api.regexp.*`
- Make global just following namespaces: `application`, `process`, `api`.
- Module local namespaces: `module`
- Handler local namespaces: `connection` or `client`

**Comment by tshemsedinov** [comment]
Something strange, after moving `JSON` to `api.json` it works, but after deleting it from global, it disappears from `api.json`
```JavaScript
global.api = {};
global.api.json = global.JSON;
delete global.JSON;
console.dir(typeof(global.api.json));
console.dir(Object.keys(global.api.json));
```
@aqrln how?

**Comment by aqrln** [comment]
@tshemsedinov even more strange that it works well in Chrome. What about Node, it doesn't disappear from `api.json`, neither do methods of `api.json`, but trying to invoke them or even retrieve `typeof` of `api.json` results in `ReferenceError`, as though it tries to resolve JSON object with its name hardcoded somewhere in V8 sources. I'll investigate the source code.

**Comment by aqrln** [comment]
@tshemsedinov and it actually is. Compare:
[src/api.cc in V8, line 2718](https://github.com/v8/v8/blob/master/src/api.cc#L2718):
```cpp
PREPARE_FOR_EXECUTION_WITH_ISOLATE(isolate, JSON, Parse, Value);
```
[deps/v8/src/api.cc in Node.js, line 2653](https://github.com/nodejs/node/blob/master/deps/v8/src/api.cc#L2653):
```cpp
PREPARE_FOR_EXECUTION_WITH_ISOLATE(isolate, "JSON::Parse", Value);
```
