### ISSUE TITLE
Remove dependency: colors

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#547]
This library changes String class just for colors. Maybe it have special mode to use functions instead of String modification or we can generete ESC colors, not a big deal

**Comment by aqrln** [comment]
> Maybe it have special mode to use functions instead of String modification

Yes, it has:

```javascript
var colors = require('colors/safe');
console.log(colors.green('Impress'));
```

**Comment by tshemsedinov** [comment]
Great, but syntax isn't good `console.log(api.colors.bold(api.colors.green('Impress')));`
What can we do with syntax? Maybe ideas from other languages/platforms?

**Comment by aqrln** [comment]
```javascript
api.tty.info = function(message) {
  return api.colors.bold(api.colors.green(message));
}
```

If we want concatenation and stuff, or, just for printing:

```javascript
api.con.info = function(message) {
  console.log(api.colors.bold(api.colors.green(message)));
}
```

**Comment by aqrln** [comment]
In the worst case:

```javascript
function functionThatPrints() {
  ...
  var bold = api.colors.bold,
      green = api.colors.green;

  console.log(bold(green('Impress'));
  ...
}
```

But that should be rare since it is an application server, not a rainbow simulation. All the combinations of colors and font styles in the chosen color scheme should be encapsulated into functions with semantic-oriented, not color-based, names.

**Comment by tshemsedinov** [comment]
Meybe something like this `api.console.log('Impress red[Application] green+bold[Server]'));`

**Comment by aqrln** [comment]
Maybe, or create a custom tag function for ES6 template strings.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals

**Comment by aqrln** [comment]
But nevertheless the idea of separate functions that form a solid color scheme, that can be easily changed in one place, and provide an abstraction over real colors seems more sensible to me.

**Comment by aqrln** [comment]
Another option is to define constants with VT100 escape sequences and use ES2015 template strings.

```js
console.log(`${api.colors.GREEN}Impress Application Server${api.colors.DEFAULT}`);
```

**Comment by tshemsedinov** [comment]
Now we use [concolor](https://github.com/metarhia/concolor) instead of `colors`
