### ISSUE TITLE
Rewrite impress.security

### ISSUE THREAD

**Issue by aqrln** [metarhia/impress#581]
Current authorization and security module in Impress is outdated and must be rewritten.

The first step is to use the standard authentication scheme nearly every framework follows with bcrypt hashing by default but decoupled from HTTP and usable with JSTP. The prototype is being developed [as a part of Metarhia Messenger](https://github.com/metarhia/Messenger/blob/master/applications/messenger/lib/api.auth.js) and will be backported to the core of Impress and integrated with it tightly.

The second step is to research zero-password-knowledge authorization and probably switch to SRP (see #572).

**Comment by tshemsedinov** [comment]
https://github.com/metarhia/Impress/issues/609
