### ISSUE TITLE
Need help in scale.js understanding

### ISSUE THREAD

**Issue by JWo1F** [metarhia/Impress#592]
Добрый день! Продолжаю копать Impress, теперь разбираю файл scale.js

**cloud** - это просто название всего облака.
**server** - ID текущего сервера. Тут не совсем понятно: внутри каждого сервера есть приложения (applications) **[1]**? Т.е. если я заливаю обновление на 3 сервера, то мне необходимо ручками (или в автоматическом режиме) менять тут значение? **[2]**
**instance** - вообще темный лес. Не понятно зачем нужно и что делает? **[3]**
**key** - как я понимаю нужен для взаимодействия двух облаков (cloud) между собой? **[4]** Если да, то как это взаимодействие реализовать? **[5]**

Вот такие 5 вопросов возникли при разборе этого файла. Нужна помощь!)

**Comment by tshemsedinov** [comment]
@JWo1F, тут вопросы на английском только, а на русском только тут: https://toster.ru/tag/node.js/questions
```js
{
  cloud: 'PrivateCloud', // имя приватного облака
  server: 'S1', // имя сервера в приватном облаке,
    // внутри каждого сервера есть воркеры и порты, домены и приложения
  instance: 'controller', // тип сервера
    // standalone - одиночный,
    // controller - контроллер прикладного облака,
    // server - сервер прикладного облака
  key: '19nm58993eJ747845fk78A2z7854W90D', // ключ подключения к контроллеру облака
}
```
