### ISSUE TITLE
Fatal error - TypeError: client.res.setHeader is not a function

### ISSUE THREAD

**Issue by dmitrystas** [metarhia/Impress#593]
Попытка создания объекта WebSocket с url, в котором не определен тип контента (расширение отсутствует или пустое) приводит к падению сервера:
`ws = api.ws('/examples/events/connect'); // Fatal error - TypeError: client.res.setHeader is not a function`

Стек ошибки:
```
  Client.defaultContentType (impress.client.js:501:16)
  Client.processing (impress.client.js:381:16)
  impress.client.js:278:16
  Client.detectRealPath (impress.client.js:728:91)
  impress.client.js:738:14
  FSReqWrap.cb [as oncomplete] (fs.js:257:19)
```

**Comment by aqrln** [comment]
Если у хендлера нет расширения, то это он не будет обслуживать WebSocket-соединения. Нужно `connect.ws`. Если очень хочется в URL не указывать расширение, то можно написать правило в `applications/.../config/routes.js`.

**Comment by dmitrystas** [comment]
Да мне ничего не хочется :) Мне расширение добавить не сложно, проблема не во мне, а в том, что кто угодно извне сможет ронять сервер.

**Comment by tshemsedinov** [comment]
@dmitrystas fixed in `0.3.17`
