### ISSUE TITLE
TypeError: api.common.metasync is not a function

### ISSUE THREAD

**Issue by JWo1F** [metarhia/Impress#594]
Если включить `intro: true` в access.js и зайти в папку (в браузере), то сыпется ошибка `TypeError: api.common.metasync is not a function` и сервер крешится. Стек:

```
impress.application.js:258:20
FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by tshemsedinov** [comment]
@dmitrystas fixed in 0.3.17
