### ISSUE TITLE
Server ignores updates of file access.js in /www/

### ISSUE THREAD

**Issue by JWo1F** [metarhia/Impress#595]
После обновления (или создания) файла access.js сервер держит в кеше его старую копию и не обновляет информацию до перезапуска сервера.

**Comment by tshemsedinov** [comment]
@JWo1F, everything works for me (Fedora & CentOS). Can you provide project/configs example, OS, node.js and Impress versions?

**Comment by JWo1F** [comment]
@tshemsedinov, okay. Steps to reproduce:

1. Create a folder (zaka for example)
2. Enter `npm i impress`
3. Clear a folder "www"
4. Start server `sh server.sh`
5. Create a file "html.template" (works very well)
6. Create a file "access.js" with `{ guests: false }`
7. Open http://localhost (WTF, but we can see html.template)
8. Restart server (Ctrl-C + sh server.sh)
9. Open http://localhost (we see 403 forbidden, all is okay)

**Comment by tshemsedinov** [comment]
Yes, this bug is actual only for `www` folder, all subfolders works well. We will fix that
