### ISSUE TITLE
TypeError: Identifier 'name' has already been declared in /app/lib/apiName.js

### ISSUE THREAD

**Issue by JWo1F** [metarhia/Impress#597]
How to reproduce:

1. create a file "/app/lib/apiName.js"
2. write `const name = "user";`
3. add some code to this (or another) file.

How to fix: wrap the code with braces: `{ const name="user" }` because const is block-scoped.

**Comment by tshemsedinov** [comment]
That is normal behavior, you should use namespaces like `api.namespace.identifier = 'value';` or use function scope or braces scope `{}`
