### ISSUE TITLE
How can I get "connection" in api?

### ISSUE THREAD

**Issue by JWo1F** [metarhia/Impress#610]
Hey there! How can I get a variable "connection" from "/api/**"?
I use `connection.domain.client`, but I think it's a bad practice.

**Comment by tshemsedinov** [comment]
Do you mean `/api` or `/www/api` ? 

For `/api` we have example here: https://github.com/metarhia/Impress/blob/master/applications/example/api/interfaceName/sendEvent.js

For `/www/api` you can use `client.req.connection`

**Comment by JWo1F** [comment]
@tshemsedinov I need to get SID or another user variable (I mean /api).

**Comment by aqrln** [comment]
@JWo1F there's no SID in `/api`. [JSTP protocol](https://github.com/metarhia/JSTP) API handlers reside there, HTTP stuff is in `/www`.

**Comment by JWo1F** [comment]
@aqrln okay. Maybe, I poorly understand what is /api.
I think it's like REST, but with JSTP instead of HTTP. I want to create some methods there. Add/update/remove/find post for example.

**Comment by aqrln** [comment]
@JWo1F no, it is not like REST. To the contrary, it is RPC.

**Comment by JWo1F** [comment]
@aqrln okay, if I need to create a method for something, but I want to delimit the rights. How can I do it?

**Comment by aqrln** [comment]
@JWo1F right now your authentication method should store a user in the connection and you'll just get it in any other method. It will work flawlessly since the connections are persistent and stateful. The standalone implementation of JSTP that will be included into Impress soon already implements protocol-level authentication and the security layer in Impress is currently being refactored too, so there will be standard facilities for doing such things.

**Comment by JWo1F** [comment]
@aqrln well, I need to create a method (auth for example) and send to it my credentials?

**Comment by aqrln** [comment]
@JWo1F yes. Let's say, you've called the interface `auth` and the method `login`.

Then it will look like this on the server side:

```javascript
// api/auth/login.js

(login, password, callback) => {
  // ...

  if (/* the credentials are correct */) {
    connection.user = /* user object */;
    callback(null, /* sessionId */);
  } else {
    callback(api.jstp.RemoteError.AUTH_FAILED);
  }
}
```

```javascript
// api/someInterface/someMethod.js

(callback) => {
  if (!connection.user || !connection.user.isAdmin()) {
    return callback(new Error('Access denied'));
  }

  // ...

  callback(null, /* result */);
}
```

And on the client side:

```javascript
let auth = null;
let someInterface = null;

function onConnect() {
  auth.login('user', 'password', (error, sessionId) => {
    if (error) {
      console.error('Could not sign in:', error);
      return;
    }

    someInterface.someMethod((error, result) => {
      if (error) {
        console.error(error);
        return;
      }

      console.log(result);
    });
  }
}

connection.handshake('applicationName', null, null, () => {
  connection.inspect('auth', (error, authProxy) => {
    if (error) {
      throw error;
    }

    auth = authProxy;
    checkCompletion();
  });

  connection.inspect('someInterface', (error, someInterfaceProxy) => {
    if (error) {
      throw error;
    }

    someInterface = someInterfaceProxy;
    checkCompletion();
  });

  function checkCompletion() {
    if (auth && someInterface) {
      onConnect();
    }
  }
});
```

**Comment by aqrln** [comment]
![risovach ru](https://cloud.githubusercontent.com/assets/4923335/19694833/7adcf3e8-9ae9-11e6-876c-160b356cd5e6.jpg)

**Comment by JWo1F** [comment]
@aqrln cool. Thanks :) I understand now.
But what to do if I want to link "login" with SID cookie, for example? Becouse I don't want to type password every time.

**Comment by aqrln** [comment]
@JWo1F there's no way to do it currently in any other way than storing username and password persistently on the client, for example, using operating system's keychain for native applications or localStorage for web apps.

**Comment by JWo1F** [comment]
@aqrln I use `connection.domain.client`. I see SID and other user fields. How it possible?

**Comment by aqrln** [comment]
@JWo1F `connection` is an `EventEmitter`, and `EventEmitter` has [domain](https://nodejs.org/dist/latest-v7.x/docs/api/domain.html). I would not recommend using it.

> there's no way to do it currently in any other way than storing username and password persistently on the client

Actually, I'm not right. You can, if your login method returns a session ID, like in the example above, and you implement another authentication method that allows you to sign in using SID.

**Comment by JWo1F** [comment]
@aqrln I mean, if I already have a SID (by security provider), I want to send it to the login method (instead of login&password). But I can't do it because this cookie is httpOnly.

**Comment by aqrln** [comment]
@JWo1F SID is not cookie. You can return it from the sign in method that takes a login and password and then pass it to a sign in method that takes a SID that you will need to implement.

**Comment by JWo1F** [comment]
@aqrln I mean SID by security provider (client.startSession, etc.)
https://github.com/metarhia/Impress/blob/master/lib/impress.security.js#L88

**Comment by aqrln** [comment]
@JWo1F and how do you use it? 😉
It requires a [`Client`](https://github.com/metarhia/Impress/blob/master/lib/impress.client.js) instance as the first argument which is bound to HTTP and there's no HTTP if you use JSTP. And if you have some HTTP client to pass there (a mock one, for example, or a `Client` subclass), then you can get your SID as `client.sid` in the login and password sign in method and later restore the user by SID with the help of `connection.application.security.getSessionUser(sid)` in the SID sign in method.

**Comment by JWo1F** [comment]
@aqrln okay. My app is:

```
api
- interface
- - simple.js
www
- api
- - login.json
- - - post.js
- - jstp.ws
- - - get.js
```

where `login.json` is:
```
(client, callback) => {
  application.security.signIn(client, client.fields.login, client.fields.password, isSuccess => {
    if (client.fields.loginForm) client.redirect('/');

    callback({ result: isSuccess ? 'ok' : 'error' });
  });
}
```

and `jstp.ws` is:
```
(client, callback) => {
  var connection = client.websocket.accept();

  if (connection) api.jstp.serveOverWebsocket(connection);

  callback();
}
```

and `simple.js` is:
```
module.exports = function(callback) {
  if(user.isAdmin()) callback(null, "success");
  else callback(api.jstp.RemoteError.AUTH_FAILED);
}
```

Steps:

1. Login in `http://localhost/api/login.json`
2. Redirect to `/`
3. In client JS open WS to `http://localhost/api/jstp.ws`
4. use it with jstp
5. how can I get a `user` variable?

**Comment by aqrln** [comment]
@JWo1F the problem is that you try to use two different mutually exclusive concepts. Either use HTTP and pure WebSocket API or experimental JSTP API. If you are brave enough to use JSTP even though it is not mature, you cannot use the standard security layer yet without modifying it heavily or implementing your own one.

**Comment by JWo1F** [comment]
@aqrln you're right. Thanks! I will use HTTP REST api :)
