### ISSUE TITLE
Why do you use bad thunks?

### ISSUE THREAD

**Issue by JWo1F** [metarhia/Impress#617]
A thunk callback is a function with two arguments: `error, [result]`. If an error isn't null we must ignore a result.

Here: https://github.com/metarhia/Impress/blob/master/lib/impress.security.mongodb.js#L82 you ignore this rule.

**Comment by tshemsedinov** [comment]
Not always:
```js
let async = require('async');
async.series({
 one: function(callback) {
   callback(null, 1);
 },
 two: function(callback) {
   callback(new Error('Oh shit!'));
 }
}, function(err, result) {
  console.dir({ err, result });
  // output: { err: Error: Oh shit! ...stack trace..., result: { one: 1, two: undefined } }
});
```
But in this place you are right, we do not need `user`.
