### ISSUE TITLE
debug on webstorm

### ISSUE THREAD

**Issue by stokaboka** [metarhia/Impress#621]
сабж...
под webstorm не работает отладчик - ias запускает несколько потоков и как следствие: EADDRINUSE
версия: 0.1.423

не работает параметр strategy: 'single' в scale.js:
Application: impress Config file: scale.js
  .strategy - Unexpected name "strategy"
т.е. всегда запускается worker

до обновления - все было ок

pls, подскажите как решить.

**Comment by tshemsedinov** [comment]
Это смесь из нескольких разных вопросов.
1. Мы не проверяем совместимость с webstorm или другими средами разработки.
2. После обновления изменилась структура конфигов, нужно взять конфиги из новой версии и сравнить их по ключам со старыми и исправить. Принципиально изменилось масштабирование, теперь всегда 1 воркер процесс на 1 серверный сокет + 1 мастер процесс. Удален нодовский модуль `cluster`, вместо него используем `child_process`. Приложения загружаются только в воркеры, в мастере не исполняется бизнес-логика. Параметр `strategy` нужно просто удалить. Обратите внимание на `/config/servers.js`.
3. Почему раньше работала отладка - не понятно, не должна была работать. Вообще вся отладка у нас логами.

**Comment by stokaboka** [comment]
ок, спасибо )
что-то придумаю. 
ias в отладчике под webstorm работал, делал свои библиотеки и было оч. удобно отлаживать. к сожалению, не могу указать версию на которой работало.
