### ISSUE TITLE
Make server state work again

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/Impress#627]
After multiple changes `impress.cloud.js` not working. We need distributed state synchronization between server nodes ASAP.

**Comment by aqrln** [comment]
@tshemsedinov this issue has been there for a while though `impress.cloud.js` has been fixed long time ago. Server events work pretty well but I am not sure that state synchronization logic itself works correctly in all cases.

IIRC, @DzyubSpirit and @belochub use `application.state`. How stable is it?

**Comment by belochub** [comment]
@aqrln
Well, it works fine for me, but I don't use all of it's features.
I think, you should test it yourself to ensure that it works correctly in all cases.
