### ISSUE TITLE
JSTP related issue with Impress 0.2.9 and Node 0.10

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/Impress#635]
Now we have Impress `0.3.30` and `0.2.9` with fixed tests, no more re connecting to cloud controller on shutdown. Multiple fixes in Impress core, refactoring and fixed fork/kill functionality. This may affect production server (not only tests). Also tests failed on Impress `0.2.9` with single Node version `0.10`. All other version, including Node `0.11` is ok: https://travis-ci.org/metarhia/Impress/builds/179303399 To run tests you can use: `npm test`. I think it is JSTP related issue.

FYI: @aqrln, @belochub

**Comment by belochub** [comment]
This issue has to do with the fact that we are using `cork` and `uncork` functions on sockets, which were added in Node `v0.11.2`.

**Comment by tshemsedinov** [comment]
I think we can stop supporting `0.10`

**Comment by aqrln** [comment]
Either we can drop support for `0.10`, or check whether `Socket#cork` is available and, if not, create a zero-filled `Buffer` instance with an extra byte and copy a packet there prior to writing to socket. Or just write a packet and a delimiter in two syscalls.
