### ISSUE TITLE
Use SSH in Impress CLI

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#640]
ssh server will give CLI to RPC
@aqrln Do you like this idea?

**Comment by aqrln** [comment]
If we need a command-line interface to remote methods, there's no point in implementing a shell server. There's nothing special in the shell itself that stops us from implementing it as a totally client-side application and we already have a JSTP server. So what we need is a generic command-line JSTP client.

**Comment by aqrln** [comment]
What about SSH, it would be nice to make `impress-cli` work with it. Thus, e.g., `impress restart` will run locally and `impress restart --host metarhia.com` will run through SSH.

**Comment by tshemsedinov** [comment]
@aqrln agreed, having Impress CLI working with JSTP we can do:
* connect to remote host over ssh and run Impress CLI there (if we have no local client and want to connect to JSTP server with just simple ssh client)
* run Impress CLI locally and connect to:
  - local Impress Server
  - remote Impress Server with full telemetry and control over server (if connected to master), over node (if connected to node), over cloud (if connected to cloud controller)

**Comment by tshemsedinov** [comment]
Old CLI will be deprecated in v2.x
