### ISSUE TITLE
Application resources

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#644]
All files (resources) from folder `applicationName/resources/` will be loaded into memory and will be reloaded on changes on disk

**Comment by tshemsedinov** [comment]
* All file types will be loaded as:
  - `string`: expensions: txt, htm, html
  - parsed JSTP data structure: *.jstp
  - `Buffer`: any other extension
* Resources will be accessible by: `application.resources[fileName]`
* Subfilders will be loaded recursive but accessible in plain hash `application.resources`

**Comment by lundibundi** [comment]
ping @tshemsedinov.
