### ISSUE TITLE
Refactor Impress to ES6

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/Impress#647]
In `master` and `v0.3.x`

Modules for @tshemsedinov:
* /lib/impress.js
* /lib/impress.application.js
* /lib/impress.client.js
* /lib/impress.security.js
* /lib/impress.cache.js
* /lib/impress.log.js
* /lib/api.common.js

Modules for @aqrln:
* https://github.com/metarhia/JSTP v0.6
* /lib/impress.jstp.js
* /lib/impress.cloud.js
* /lib/impress.state.js
* /lib/impress.websocket.js

**Comment by tshemsedinov** [comment]
Started from common lib because of dependencies: https://github.com/metarhia/Impress/commit/1b07e4131ae728bb14254a38767076aabc176b1f

**Comment by aqrln** [comment]
ESLint rules for ES2015: https://github.com/metarhia/JSTP/commit/9c6871923b58c50e948d89005eea0b80960a4246

**Comment by tshemsedinov** [comment]
I think we will publish refactored code as Impress `v0.4`
So waiting for JSTP `v0.6.0` published to npm for publishing Impress `v0.4.0`
@aqrln
