### ISSUE TITLE
Install with no root permissions

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#648]
Now Impress requires root permissions to be installed, but we need at least 3 installation types:
* Impress core developer (not root)
* Application developer (not root)
* Production server instance (root)

**Comment by aqrln** [comment]
And how's that different from the current model? As Impress core developer and applications developer I don't have Impress installed under root on my machine and it works perfectly fine. As far as I have always understood and done, scripts in `deploy` directory are meant for production servers, Impress core developers just need no do `git clone` and application developers must, firstly, `npm install impress` for each project and copy server configs and stuff or just clone the project template and, secondly, optionally `npm install -g impress-cli`.

The only thing I think is missing is project creation and scaffolding in `impress-cli`, but that is already discussed (#487, metarhia/ImpressCLI#9, metarhia/ImpressCLI#10).
