### ISSUE TITLE
Review `for-in` loops

### ISSUE THREAD

**Issue by aqrln** [metarhia/Impress#679]
There's a lot of `for-in` loops throughout the codebase, with at least one of uses found in code under load. We need to review them and possibly change to `Obect.keys()` iteration.

**Comment by tshemsedinov** [comment]
Here is some related optimizations https://github.com/metarhia/Impress/tree/cache-opt

**Comment by tshemsedinov** [comment]
I made tests and somehow it appears that for-in works quick. @aqrln 
[HowProgrammingWorks/Benchmark/JavaScript/9-for-in.js](https://github.com/HowProgrammingWorks/Benchmark/blob/master/JavaScript/9-for-in.js)
```
testForKeys.............260940518 nanoseconds
testForIn...............239195703 nanoseconds
testForInLet............178031667 nanoseconds
testForOf...............861155431 nanoseconds
testForOfLet............827801831 nanoseconds
```

**Comment by aqrln** [comment]
@tshemsedinov thanks, I'll check it out a bit later.

**Comment by aqrln** [comment]
For-in loops are fast in modern V8 versions, I was operating a bit outdated information when I opened the issue, so I'm going to go ahead and close it.
