### ISSUE TITLE
Refactor `impress.application.js`

### ISSUE THREAD

**Issue by aqrln** [metarhia/Impress#681]
* [ ] https://github.com/metarhia/Impress/pull/676/files#diff-25c29526b468ed8fd0f81af4549c3542R313
* [ ] https://github.com/metarhia/Impress/pull/676/files#diff-888ed8961847bf1c76dd7c2eb8f07e53R68
* [ ] https://github.com/metarhia/Impress/pull/676/files#diff-888ed8961847bf1c76dd7c2eb8f07e53R77

**Comment by tshemsedinov** [comment]
@aqrln if you mean moving cache updated for different extension and places to separate functions, extensions are already moved but I do not think we need to do that for places: function are small enough, extension handlers have high code coupling.

**Comment by aqrln** [comment]
@tshemsedinov yeah, it already looks much prettier with extension handlers moved to separate functions and place handlers kept inline.
