### ISSUE TITLE
Test memory cache optimizations

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#696]
As you know we load static files and handlers to memory and watching for file system changes.
@belochub here is a branch with cache optimizations https://github.com/metarhia/Impress/tree/cache-opt
It works for a first look, I changes a few files and they are loaded.
But please test multiple cases: renaming, changing directories, etc.

**Comment by belochub** [comment]
I did some tests on examples of HTTP parts of Impress and it works fine now.
Could not test for JSTP API because of some problems with starting it (see #697).

**Comment by tshemsedinov** [comment]
@belochub rebased

**Comment by tshemsedinov** [comment]
See https://github.com/metarhia/Impress/pull/700
Maybe we can use Set instead of array. Speed tests needed.
