### ISSUE TITLE
Include certbot to deploy scripts

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#735]
It would be great to integrate letsencrypt auto generated certificates to Impress but first step will be adding certbot to `/deploy/*.sh` scripts with `EPEL 7` dependency

**Comment by o-rumiantsev** [comment]
I will do this.

**Comment by belochub** [comment]
As a starting point, you can take a look at the installation script for Metarhia server: https://github.com/metarhia/server/blob/master/install.sh
