### ISSUE TITLE
JSTP ignores address and always listens to all interfaces

### ISSUE THREAD

**Issue by dmitrystas** [metarhia/impress#740]
Server with protocol 'jstp' ignores the setting 'address' and always listens to all interfaces.

For example, in \config\servers.js we have

>   master: {
>     protocol:  'jstp',
>     transport: 'tcp',
>     **address:   '127.0.0.1'**,
>     ports:     [250],
>     slowTime:  '1s'
>   },
> 

but after start port 250 is open not only on the local interface.

It`s happens because when we creating server we does not specify the host. For examle in \node_modules\metarhia-jstp\lib\transport.socket.js we have only this.port

> this.server.listen(this.port, callback);

and no hostname or ip

**Comment by tshemsedinov** [comment]
@aqrln please check this

**Comment by aqrln** [comment]
@dmitrystas yeah, that's a known issue that is fixed in the upcoming release of [metarhia/jstp](https://github.com/metarhia/jstp) as a part of https://github.com/metarhia/jstp/pull/209. If you need a quick fix, I think we can make a patch for v0.6 too. Thanks for reporting it!

**Comment by tshemsedinov** [comment]
@belochub  please review this to close or reassign
