### ISSUE TITLE
CentOS crashes

### ISSUE THREAD

**Issue by ykolomiets** [metarhia/impress#742]
We are experiencing occasional crashes on CentOS server. What may be the reason of these issues and how can we overcome them. Screenshots attached, thank you in advance!
![crash2](https://user-images.githubusercontent.com/24361808/27229008-914c19ca-52b2-11e7-8641-b8c11c4bd334.png)
![crash1](https://user-images.githubusercontent.com/24361808/27229007-91460cce-52b2-11e7-8e65-569f606b26f1.png)

**Comment by belochub** [comment]
May you please provide the output of `impress version`, if you have `impress-cli` installed, or the output of `npm list` otherwise?

**Comment by aqrln** [comment]
I'd be especially interested in `npm list | grep metarhia-jstp`.

**Comment by belochub** [comment]
@aqrln, it may be not enough, because it is probably included in multiple packages.

**Comment by tshemsedinov** [comment]
@ykolomiets it would be great to get full stack trace in textual format.

**Comment by ykolomiets** [comment]
[version.txt](https://github.com/metarhia/impress/files/1081808/version.txt)

**Comment by tshemsedinov** [comment]
@ykolomiets please check Impress version, it somehow not included (maybe impress-cli can't find Impress folder).

**Comment by ykolomiets** [comment]
impress@0.3.29

**Comment by tshemsedinov** [comment]
It would be better to move project to `impress@0.4` but we are supporting `0.3.x` as well, so thanks and we will try to find your problem. It may require additional info, so thanks for your report and providing debugging info @ykolomiets

**Comment by ykolomiets** [comment]
Maybe these logs will help you

**Comment by belochub** [comment]
@ykolomiets, what about `npm list`, can you share its output, please? It will help us to identify the problem.

**Comment by ykolomiets** [comment]
[2017-06-09-node.txt](https://github.com/metarhia/impress/files/1081850/2017-06-09-node.txt)
[2017-06-09-server.txt](https://github.com/metarhia/impress/files/1081851/2017-06-09-server.txt)

**Comment by ykolomiets** [comment]
[list.txt](https://github.com/metarhia/impress/files/1081864/list.txt)

**Comment by ykolomiets** [comment]
And I have one more question. If I turn off wi-fi on client, can I find out this on server?

**Comment by belochub** [comment]
@ykolomiets, apparently, you are using a very outdated version of `metarhia-jstp` package (0.4.2) which had some bugs in the parser, that can lead to errors like the one on the first screenshot here https://github.com/metarhia/impress/issues/742#issue-236486437.
Please update it to a newer version using `npm update`, preferably `0.6.x`, but it can be `0.5.x` as well because it got almost all of the important fixes backported.

> And I have one more question. If I turn off wi-fi on client, can I find out this on server?

You can add a listener to the `close` event on any connection, it will be emitted any time client closes the connection in any way (like the one you mentioned, for example). Although, this can happen with a little bit of delay, due to the way TCP works.

**Comment by ykolomiets** [comment]
Thanks, we will update) I added a listener and mark that connection close on client that moment when I turn off wi-fi, but on server I can see this after minute or more

**Comment by belochub** [comment]
Yeah, it can be like that sometimes, for this case specifically we added heartbeat packets in JSTP, which are enabled by default in the newer versions, updating the package will help you with this problem as well.

**Comment by ykolomiets** [comment]
Thanks again

**Comment by ykolomiets** [comment]
Do you have JSTP client realization on C#?

**Comment by aqrln** [comment]
@ykolomiets nope, not yet. @Raixur used to work on it a while ago (https://github.com/JSTPKPI/JSTP-CS), so you may fork it and take it over if you are interested.
