### ISSUE TITLE
Set cookies when connecting to websocket

### ISSUE THREAD

**Issue by dmitrystas** [metarhia/impress#743]
The WebSocket library (which is used in Impress) can set cookies. But this functionality not implemented in Impress. To do this we need add only one parameter to function ws.accept in impress.websocket.js

```
ws.accept = (**cookies**) => {
	ws.isAccepted = true;
	client.res.statusCode = 101;
	client.accessLog();
	if (ws.fake) return;
	return ws.request.accept('', ws.request.origin, **cookies**);
};
```

And now we can set cookies in our handlers (for example in \applications\example\www\examples\events\connect.ws\get.js)

```
(client, callback) => {
	var cookies = [
		{
			name: 'TestCookie',
			value: 'CookieValue' + Math.floor(Math.random()*1000),
			path: '/',
			secure: false,
			maxage: 5000,
			httponly: true
		}
	];
	const connection = client.websocket.accept(cookies);
	...
}
```

**Comment by tshemsedinov** [comment]
Fixed in `0.4.21`
