### ISSUE TITLE
Logging mysql`s and pqsql`s queries

### ISSUE THREAD

**Issue by dmitrystas** [metarhia/impress#746]
In api.db.mysql.js and api.db.pqsql.js all queries are logged to debug log.

```
    connection.on('query', (err, res, fields, query) => {
      ...
      application.log.debug(query.sql);
    });

```

Just not removed after the tests? Or for what this feature in production?

**Comment by tshemsedinov** [comment]
Logging all SQL statements is a common practice for production in bloody enterprise. But you can disable it just removing `debug` in `config/log.js`

**Comment by dmitrystas** [comment]
Ok, thanx.
