### ISSUE TITLE
Can not install Impress after update node.js to 8.3.0

### ISSUE THREAD

**Issue by dmitrystas** [metarhia/impress#756]
After update node.js to version 8.3.0 when I tried to restart Impress got the error

> Impress Application Server 0.4.22
> 
> Failed to start Impress Application Server
> See logs in /ias/log/ for details

After that I removed Impress and tried to install it again, but got the error

> Impress Application Server 0.4.22
> Error: Command failed: ./bin/install.sh

**Comment by dmitrystas** [comment]
As you can see in the previous message, I first updated Impress, and then updated Node.js.

Today I tried first to update Node.js (from 8.2.1 to 8.3.0), and then update Impress (from 0.4.21 to 0.4.22). The output when updating is:

> root@debian:/ias# impress update
> Impress Application Server 0.4.21
> /usr/bin/impress -> /usr/lib/node_modules/impress-cli/cli.js
> 
> > impress-cli@0.4.22 install /usr/lib/node_modules/impress-cli
> > node install.js
> 
> Impress Application Server CLI
> Error: Command failed: chmod +x ./bin/install.sh
> chmod: changing permissions of ‘./bin/install.sh’: Operation not permitted
> 
> Error: Command failed: ./bin/install.sh
> chmod: changing permissions of ‘/usr/lib/node_modules/impress-cli/bin/uninstall.sh’: Operation not permitted
> chmod: changing permissions of ‘/usr/lib/node_modules/impress-cli/bin/impress’: Operation not permitted
> ln: cannot remove ‘/bin/impress’: Permission denied
> rm: cannot remove ‘/etc/init.d/impress’: Permission denied
> ln: cannot remove ‘/etc/init.d/impress’: Permission denied
> rm: cannot remove ‘/etc/systemd/system/impress.service’: Permission denied
> ln: cannot remove ‘/etc/systemd/system/impress.service’: Permission denied
> Failed to execute operation: Access denied
> Synchronizing state for impress.service with sysvinit using update-rc.d...
> Executing /usr/sbin/update-rc.d impress defaults
> insserv: fopen(.depend.stop): Permission denied
> Failed to execute operation: Access denied
> Executing /usr/sbin/update-rc.d impress enable
> insserv: fopen(.depend.stop): Permission denied
> Failed to execute operation: Access denied
> Failed to execute operation: Access denied
> 
> + impress-cli@0.4.22
> added 1 package and updated 2 packages in 3.053s
> 
> > impress@0.4.22 install /ias/node_modules/impress
> > node install.js
> 
> Impress Application Server is already installed and configured in this folder.
> + impress@0.4.22
> added 5 packages, removed 5 packages, updated 15 packages and moved 3 packages in 9.545s

Maybe this can help.

**Comment by dmitrystas** [comment]
Clean install on clean OS with Node 8.3.0

> root@debian:/impress# npm install impress

> Installing Impress Application Server...
> 
> /usr/bin/impress -> /usr/lib/node_modules/impress-cli/cli.js
> 
> > impress-cli@0.4.22 install /usr/lib/node_modules/impress-cli
> > node install.js
> 
> Impress Application Server CLI
> 
> Error: Command failed: ./bin/install.sh
> Synchronizing state for impress.service with sysvinit using update-rc.d...
> Executing /usr/sbin/update-rc.d impress defaults
> Executing /usr/sbin/update-rc.d impress enable
> 
> + impress-cli@0.4.22
> added 7 packages in 2.173s
> 
> Impress Application Server 0.4.22
>   Path: /impress
> 
> Impress Application Server 0.4.22
> Error: Command failed: ./bin/install.sh
> Synchronizing state for impress.service with sysvinit using update-rc.d...
> Executing /usr/sbin/update-rc.d impress defaults
> Executing /usr/sbin/update-rc.d impress enable
> 
> Installed to autostart on system boot
> 
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN enoent ENOENT: no such file or directory, open '/impress/package.json'
> npm WARN impress No description
> npm WARN impress No repository field.
> npm WARN impress No README data
> npm WARN impress No license field.
> 
> + impress@0.4.22
> added 152 packages in 22.031s

**Comment by tshemsedinov** [comment]
I hope we fixed it in 0.4.24, please check your case

**Comment by tshemsedinov** [comment]
@belochub see what we have now:
```
[marcus@Metarhia TEMP]$ npm install impress

> websocket@1.0.24 install /home/marcus/TEMP/node_modules/websocket
> metarhia-jstp@0.6.8 install /home/marcus/TEMP/node_modules/metarhia-jstp
> metarhia-jstp@0.6.8 rebuild-node /home/marcus/TEMP/node_modules/metarhia-jstp
> bcrypt@1.0.2 install /home/marcus/TEMP/node_modules/bcrypt
> impress@0.4.24 install /home/marcus/TEMP/node_modules/impress
> node install.js

Installing Impress Application Server...

/home/marcus/.nvm/versions/node/v8.4.0/bin/impress -> /home/marcus/.nvm/versions/node/v8.4.0/lib/node_modules/impress-cli/cli.js

> impress-cli@0.4.23 install /home/marcus/.nvm/versions/node/v8.4.0/lib/node_modules/impress-cli
> node install.js

Impress Application Server CLI

Error: Command failed: ./bin/install.sh
ln: failed to create symbolic link '/bin/impress': Permission denied
rm: cannot remove '/etc/init.d/impress': Permission denied
ln: failed to create hard link '/etc/init.d/impress' => '/home/marcus/.nvm/versions/node/v8.4.0/lib/node_modules/impress-cli/bin/impress': Permission denied
rm: cannot remove '/etc/systemd/system/impress.service': Permission denied
ln: failed to create hard link '/etc/systemd/system/impress.service' => '/home/marcus/.nvm/versions/node/v8.4.0/lib/node_modules/impress-cli/bin/impress.service': Permission denied
Synchronizing state of impress.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable impress
You do not have enough privileges to perform this operation.

+ impress-cli@0.4.23
added 7 packages in 6.46s

Impress Application Server 
  Path: /home/marcus/TEMP

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/marcus/TEMP/package.json'
npm WARN TEMP No description
npm WARN TEMP No repository field.
npm WARN TEMP No README data
npm WARN TEMP No license field.

+ impress@0.4.24
added 158 packages in 40.157s
```

**Comment by tshemsedinov** [comment]
After 20b7dfca2b34138475d85d85b58360e8e7a42949 it still fails but with less errors:
```
Impress Application Server CLI

Error: Command failed: sudo ./bin/install.sh
Synchronizing state of impress.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable impress
```

**Comment by tshemsedinov** [comment]
Maybe we can remove multiple `sudo` from `install.sh` if we run it `sudo install.sh` but we need more experiments here and I don't know can we avoid publishing it to npm.
