### ISSUE TITLE
Initialization order

### ISSUE THREAD

**Issue by nechaido** [metarhia/impress#780]
While working on integrating current version of JSTP into Impress, I have discovered that it is needed for `impress.applications` to be initialized before calling `impress.jstp.createServer()` in `impress.js:446`.

**Comment by nechaido** [comment]
It's not needed anymore to integrate `jstp@1` but I still think that applications should be loaded before starting servers, @tshemsedinov what do you think?

**Comment by tshemsedinov** [comment]
Initialization order was refactored here https://github.com/metarhia/impress/pull/935/commits/f3bdbc4732f668413973818dcbfe120f9196c411 and in a few commits in this PR: https://github.com/metarhia/impress/pull/935
