### ISSUE TITLE
How to debug causing 100% CPU usage?

### ISSUE THREAD

**Issue by dmitrystas** [metarhia/impress#783]
Periodically I see 100% CPU usage by S1N1. When I try to stop Impress (impress stop) I see something like this:

> root@server:/ias# impress stop
> Impress Application Server 0.4.26
> 
> Stopped
> root@server:/ias# impress status
> Impress Application Server 0.4.26
> USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
> root     31802 13.8 15.0 1481060 308980 pts/1  Rl   Oct28 113:51 impress S1N1

As you can see the process S1N1 does not unloaded from memory after "impress stop". And still 100% CPU usage. After reboot everything is fine, but after some time the problem recurs.

Is no info in log files about this - error.log, warning.log, slow.log are empty.

How can I understand what is wrong?

Thanx.

**Comment by johnbizokk** [comment]
@dmitrystas Hi! As I know (in my case - ```0.4.20```, latest version with low memory consumption), you need to stop the slave processes manually. The first step implies that you get PID of slave processes and the second step is to gracefully stop them. Example:
 
```kill -15 $(ps aux | grep impress | awk '{if(NR>1)print $2}')``` * the result may depend on the shell

**Comment by dmitrystas** [comment]
@johnbizokk, Hi!

You`re right, it will help with service stopping. But how to understand what the cause of the problem? For examle in "clean" nodejs (without Impress) we can use V8 Profiler
`node --prof app.js`
And what about Impress? How can I catch the 100% CPU usage in Impress?

**Comment by tshemsedinov** [comment]
I believe this is fixed in `1.x`
