### ISSUE TITLE
Test and improve impress installation

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#786]
I think we have many complaints about installation problems after latest node and npm updates, so need to check and fix this.

**Comment by tshemsedinov** [comment]
What about autostart?

**Comment by o-rumiantsev** [comment]
> What about autostart?

Forgot about this. Will check it as soon as possible

**Comment by tshemsedinov** [comment]
Try to install impress from user account not from root. It would be good it we can install under user but it there are problems we must give prompt for sudo or at least print readable warning.

**Comment by tshemsedinov** [comment]
Also try `npm test` after installation

**Comment by o-rumiantsev** [comment]
I checked what you said on Ubuntu, Debian, Fedora and CentOS, and got such results:
* Autostart does not work on Ubuntu and Debian, there are some error output:

```
Ubuntu

Error: Command failed: sudo ./bin/install.sh
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
  LANGUAGE = (unset),
  LC_ALL = (unset),
  LC_TIME = "uk_UA.UTF-8",
  LC_MONETARY = "uk_UA.UTF-8",
  LC_ADDRESS = "uk_UA.UTF-8",
  LC_TELEPHONE = "uk_UA.UTF-8",
  LC_NAME = "uk_UA.UTF-8",
  LC_MEASUREMENT = "uk_UA.UTF-8",
  LC_IDENTIFICATION = "uk_UA.UTF-8",
  LC_NUMERIC = "uk_UA.UTF-8",
  LC_PAPER = "uk_UA.UTF-8",
  LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
update-rc.d: error: unable to read /etc/init.d/impress
```
```
Debian

Error: Command failed: sudo ./bin/install.sh
update-rc.d: error: unable to read /etc/init.d/impress
```
* Autostart works on Fedora and CentOS, but also outputs some errors like
```
Error: Command failed: sudo ./bin/install.sh
```
or
```
Error: Command failed: sudo ./bin/install.sh
Created symlink /etc/systemd/system/multi-user.target.wants/impress.service → /etc/systemd/system/impress.service.
```
* Installing not under root user and `npm test` does not work anywhere. npm says that there is nothing to test. I checked `package.json` and found that everywhere it looks like this
```
{
  "name": "example",
  "version": "1.0.0",
  "private": true,
  "description": "Impress Application Server instance",
  "dependencies": {
    "impress": "^0.6.3"
  },
  "engines": {
    "node": ">=0.6.0"
  }
}
```
