### ISSUE TITLE
Upgrade deploy scripts to nodejs 9.x

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#789]
We need to upgrade all scripts here https://github.com/metarhia/impress/tree/master/deploy from `7.x` to `9.x` and test on virtual machines. @belochub you can give this tasks to ours new guys.

**Comment by tshemsedinov** [comment]
https://github.com/metarhia/impress/tree/master/deploy

**Comment by belochub** [comment]
Closed in https://github.com/metarhia/impress/commit/7b6b8416da2c75c2e77a43b4eaa0149efeeb02b0.
