### ISSUE TITLE
Integrate tests into application structure

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#793]
~~`/applications/{name}/tests`~~

**Comment by ykolomiets** [comment]
Hi, guys. Do you have progress in providing this feature? What is the best way to integrate tests in our project? For example in file applications/testApp/shop.js we have:
```
api.testApp.buyItem = (userId, itemId, callback) => {
  const item = getItem(itemId);
  if (user.cash < item.price)
    return callback(shopErrors.NOT_ENOUGH_MONEY);

  user.cash -= item.price;
  user.items.push(item);
  callback(null);
};
```
where should i put tests and how can i access api.testApp.buyItem function?

**Comment by ykolomiets** [comment]
@tshemsedinov @aqrln

**Comment by nechaido** [comment]
@tshemsedinov I would like to implement this if you provide some more specification on the subject.

**Comment by tshemsedinov** [comment]
We'll do that later, maybe in August @nechaido

**Comment by ykolomiets** [comment]
@tshemsedinov, @nechaido any progress?

**Comment by tshemsedinov** [comment]
We decided to implement following:
- Unittest will be stored inside certain application in `lib/${submoduleName}.test.js` files
- System, end-to-end and integration tests will be stored in `lib/test/${testName}.js` files
- Tests will be started if `IMPRESS_MODE=test`, Impress will start then execute unittests and `lib/test`. After all tests finished Impress will shutdown.

**Comment by nechaido** [comment]
@tshemsedinov IIUC test should be only run for master server, am I right?

**Comment by tshemsedinov** [comment]
Yes, for first implementation I'll implement test runner in master process, but in future it's better to run separate worker for it. @nechaido

**Comment by tshemsedinov** [comment]
I see you want to implement this issue. Ok, but note that we need new type of forking and I think you may quickly implement temporary solution to run unit-tests in one of workers (first I think) because master will not load any application. Then I'll help with separate worker for tests.

**Comment by nechaido** [comment]
@tshemsedinov AFAIU this can be closed.
