### ISSUE TITLE
Server crash if package has '\n'

### ISSUE THREAD

**Issue by ykolomiets** [metarhia/impress#811]
Hi, guys! I have a new problem. If in my server call presents '\n' then server crash without any information.
Example: in our project, we have a chat, and if user enters a message with line break then we have a crash. In metarhia-jstp/lib/transport.socket.js I added some console.logs

```js
SocketTransport.prototype._onSocketData = function(chunk) {
  const packets = [];
  this._buffer += chunk;

  console.log('Buffer: ' + JSON.stringify(this._buffer));
  try {
    this._buffer = jsrs.parseNetworkPackets(this._buffer, packets);
    console.log('Parsed: ' + packets.length);
  } catch (error) {
     console.log('Parsing error: ' + error);
     this.emit('error', error);
     return;
  }
   const packetsCount = packets.length;
   for (let i = 0; i < packetsCount; i++) {
       this.emit('packet', packets[i]);
   }

   if (this._buffer.length > MAX_PACKET_SIZE) {
     this.emit('error', new Error('Maximal packet size exceeded'));
    }
  };
```
and have following output: 
```
Buffer: "{ping:[1]}\u0000"
Parsed: 1

Buffer: "{call:[2,'test'],postmessage:['\n']}\u0000"
```
That`s all. All connections close, and I need stop impress and start it again.

**Comment by belochub** [comment]
Hello!
I've tried to reproduce the issue on the latest version of `impress` and I wasn't able to get the result you reported.
By looking at the code of the local version of `metarhia-jstp` package you provided, it seems that you are using a severely outdated version of the package, which may have some bugs in the parsing/serialization implementations.
I'd recommend updating to the latest version of `metarhia-jstp` and `impress` packages, this may fix this issue for you.

**Comment by ykolomiets** [comment]
Sorry, my bad

**Comment by ykolomiets** [comment]
Now, I`m really updated.
"impress": "^0.5.1",
"impress-cli": "^0.4.26"

But I have a lot of errors cause my previous version of impress was ^0.4.29.
Where can I read changelog?

**Comment by ykolomiets** [comment]
Well done, guys! Now server doesn't crash on '\n' in the message, just closes connection with client.

**Comment by aqrln** [comment]
@ykolomiets do you use the official JavaScript client library or do you implement it (supposedly in other language) yourself? As far as I can tell from the log output in your first post, the message that the client sends is invalid and triggers a legit syntax error.

**Comment by ykolomiets** [comment]
@aqrln , that`s what server receives "{call:[2,'test'],postmessage:['\n']}\u0000". Is it legit?

**Comment by nechaido** [comment]
@ykolomiets it is not, `\n` must be escaped in string literals. Correct message would be:

`"{call:[2,'test'],postmessage:['\\n']}\u0000"`

**Comment by ykolomiets** [comment]
@nechaido, well done. Solved!

**Comment by aqrln** [comment]
@ykolomiets sorry for missing your reply, but, fwiw, no, it's not, as @nechaido has already said above. Just to clarify and to be sure you get the full picture, it wasn't even what the server received, but rather the result of `JSON.stringify()` in the 5th line of the snippet in the first post, so the `\n` thingie in the log output was a deception that might have been hard to notice at first glance. The actual data was:

```
{call:[2,'test'],postmessage:['
']}
```

and it's clearly not a valid JSON5 or JavaScript syntax. Similar issues might exist with other special characters too.

**If you use JavaScript to develop the client-side app**, I'd strongly suggest using the [metarhia-jstp](https://github.com/metarhia/jstp) library to avoid this kind of issues. For serialization per se,

```js
const serialized = jstp.stringify(value);
```

would stringify anything from strings and scalars to complex JavaScript objects correctly, with proper formatting and escaping, and its counterpart `jstp.parse(serialized)` would do the opposite — think `JSON.stringify()`/`JSON.parse()` for JSTP-flavored JSON5.

However, you'd virtually never use these functions directly (unless for logging and the like) — the high-level API abstracts and encapsulates that away, as well as it does the underlying protocol and other implementation details. Making a request to the server in JSTP looks like calling an ordinary JavaScript function — in your case, something like

```js
api.test.postmessage(text, callback);
```

**If that's not the case**, though, **and you have to implement both the protocol and data marshalling in other language yourself**, the following resources would most probably be useful to you:

* [reference C++ parser implementation](https://github.com/metarhia/jstp/tree/master/src)
* [reference JavaScript serializer implementation](https://github.com/metarhia/jstp/blob/master/lib/stringify.js)
* [reference JavaScript parser implementation](https://github.com/metarhia/jstp/blob/master/lib/serde-fallback.js)
* [JSON5 test suite adapted for JSTP](https://github.com/metarhia/jstp/tree/master/test/fixtures/json5)
* [JSTP's own serialization/deserialization test case](https://github.com/metarhia/jstp/tree/master/test/fixtures/serde-test-cases)

The C++ parser is tightly coupled with V8 API and data types for performance reasons, so it's not reusable out-of-the-box, but decoupling it is probably easier than writing a new one from scratch, especially given the optimizations.

As a starting point for a simpler solution that compiles down to machine code and uses native data structures, I had an extremely small and simple parser built using [parser combinators](https://en.wikipedia.org/wiki/Parser_combinator) with [nom](https://github.com/Geal/nom) in Rust somewhere, made as an experiment half a year ago or so. It was written in one pass in several hours without any debugging or even reading the code, not to mention optimizing it. With a  wrapper that provided conversion between native types and V8's managed JavaScript values (for simplicity sake, with lots of slow heap allocations that could be alleviated with external strings and typed arrays), it was able to power JSTP and pass the most of the test suite, however. I haven't published it anywhere, so let me know if it could of use or helpful.

For the reverse operation, the simplest and fastest way to implement a JSTP-compatible, correct and safe serializer in any language is to use a JSON serializer: the only visible difference is single-quotes vs double-quotes, but it doesn't really matter, pragmatically speaking.

**Comment by ykolomiets** [comment]
Thanks a lot, I have written simple implementation of JSTP client and JSON5 in C#. I found mistake with \n and fixed it, but now I have problem with single qoute, no error, just ignoring this symbol. I will read info that you provide, fix all issues and share C# implementation of JSTP if your are inyeresting in it)
