### ISSUE TITLE
Can not log from init scripts 

### ISSUE THREAD

**Issue by nechaido** [metarhia/impress#847]
When I try to debug log something from init scripts, the process fails:
```
2018-07-04T15:11:24.542Z         error          /applications/goliath/init/test.js:10
application.log.debug('message');
                ^

TypeError: application.log.debug is not a function
        /applications/goliath/init/test.js:10:17
        ContextifyScript.Script.runInContext (vm.js:59:29)
        EventEmitter.application.prepareScript (/impress/lib/application.js:154:30)
        api.fs.readFile (/impress/lib/application.js:178:31)
        FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

```
Impress version is: "0.6.2".

**Comment by nechaido** [comment]
Upon further investigation, it appears that `console.log`, `console.error` and `console.debug` work just fine. Should I use `console` instead of `applcation.log`?

**Comment by tshemsedinov** [comment]
@nechaido, yes, `application.log` is deprecated, you can use `console.log` and all `console` methods: `assert, clear, count, countReset, time, timeEnd, log, dir, debug, error, trace, warn, info, group, groupCollapsed, groupEnd`
