### ISSUE TITLE
Remove mongodb and add pg in deploy script

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#878]
Remove `*-mongo.sh` https://github.com/metarhia/impress/tree/master/deploy
Add `*-pgsql.sh` for all operation systems

@nechaido I propose this task for @o-rumiantsev

**Comment by belochub** [comment]
@tshemsedinov, this issue's title contradicts the description, probably a typo:
>Remove mongodb and **add** pg in deploy script
>**Remove** `*-pgsql.sh` for all operation systems

**Comment by tshemsedinov** [comment]
@belochub thanks, fixed
