### ISSUE TITLE
Profiling and optimizations

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#956]
We may start with `node --prof server.js` and apache benchmark
For example: `ab -k -c 100 -n 50000 127.0.0.1/examples/simple/jsonGet.json`

See:
- https://nodejs.org/en/docs/guides/simple-profiling/
- http://httpd.apache.org/docs/2.2/programs/ab.html

Guys, please assign somebody to this important but not urgent issue
@lundibundi @belochub @nechaido

**Comment by lundibundi** [comment]
Also, I'd recommend using https://github.com/mcollina/autocannon or https://github.com/giltene/wrk2.

You may find useful any flame graph visualization tool (e.g. https://github.com/mapbox/flamebearer or even simple v8s v8/tools/profview/index.html).

**Comment by aqrln** [comment]
+1 to @lundibundi's suggestion, I have no experience with `autocannon`, but `wrk`/`wrk2` are way more modern, can produce a lot more load than `ab` and, while being simple to use out-of-the box, support sophisticated testing scenarios written as Lua scripts when you need that. Also keep in mind that `ab` is HTTP/1.0 only and doesn't support keep-alive.

**Comment by tshemsedinov** [comment]
`ab` supports `keep-alive` with `-k` switch but you are right it's a part of archaic web, let's use something new and node-related, if we have something

**Comment by bugagashenkj** [comment]
I, with @lundibundi, investigated this question. Impress falls on HTTP requests with error.
```
2018-12-14T08:05:52.335Z	 error  	HTTP 404	Not Found	/
2018-12-14T08:05:52.339Z	 error  	TypeError: this.application.accessLog is not a function
	Client.end (/impress/lib/client.js:351:46)
	include (/impress/lib/client.js:414:16)
	done (/impress/lib/client.js:1059:7)
	Immediate.next (/metasync/lib/array.js:181:7)
	processImmediate (timers.js:632:19)
	process.topLevelDomainCallback (domain.js:120:23)

```

**Comment by tshemsedinov** [comment]
@bugagashenkj how to reproduce?

**Comment by bugagashenkj** [comment]
autocannon -c 1 -d 5

**Comment by bugagashenkj** [comment]
https://gist.github.com/bugagashenkj/77508fde0672e32533aeb662ce516b93

**Comment by tshemsedinov** [comment]
@bugagashenkj @belochub I tried to use new `vm` api to avoid `runInContext` but this need more research and experiments to compare. See this branch: https://github.com/metarhia/impress/tree/compile-func

**Comment by tshemsedinov** [comment]
@bugagashenkj we have significantly improved performance in `Version 1.0.0-alpha.10`

**Comment by VikiD** [comment]
Might be interesting to check this blog, really structured information regarding node.js
[https://os-system.com/blog/12-types-of-node-js-applications-with-examples/](url)
